// Generado por scripts/embed-migrations.mjs (npm run db:generate). No editar a mano.
export const MIGRATIONS: { id: string; statements: string[] }[] = [
  {
    "id": "0000_init",
    "statements": [
      "CREATE TABLE `activity` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`league_id` integer NOT NULL,\n\t`text` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`league_id`) REFERENCES `leagues`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `activity_league_idx` ON `activity` (`league_id`,`created_at`);",
      "CREATE TABLE `bids` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`listing_id` integer NOT NULL,\n\t`member_id` integer NOT NULL,\n\t`amount` integer NOT NULL,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`listing_id`) REFERENCES `listings`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`member_id`) REFERENCES `members`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE UNIQUE INDEX `bids_listing_member_uq` ON `bids` (`listing_id`,`member_id`);",
      "CREATE TABLE `club_teams` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`short_name` text NOT NULL,\n\t`gender` text NOT NULL,\n\t`competition` text NOT NULL,\n\t`federation` text DEFAULT 'FCF' NOT NULL,\n\t`federation_url` text,\n\t`sort` integer DEFAULT 0 NOT NULL\n);",
      "CREATE TABLE `gameweeks` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`number` integer NOT NULL,\n\t`name` text NOT NULL,\n\t`deadline` integer NOT NULL\n);",
      "CREATE UNIQUE INDEX `gameweeks_number_unique` ON `gameweeks` (`number`);",
      "CREATE TABLE `leagues` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text NOT NULL,\n\t`is_public` integer DEFAULT false NOT NULL,\n\t`code` text NOT NULL,\n\t`owner_id` integer,\n\t`starting_cash` integer DEFAULT 20000000 NOT NULL,\n\t`max_members` integer DEFAULT 8 NOT NULL,\n\t`market_size` integer DEFAULT 8 NOT NULL,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`owner_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE UNIQUE INDEX `leagues_code_unique` ON `leagues` (`code`);",
      "CREATE TABLE `lineups` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`member_id` integer NOT NULL,\n\t`gameweek_id` integer NOT NULL,\n\t`formation` text NOT NULL,\n\t`player_ids` text NOT NULL,\n\t`captain_id` integer,\n\tFOREIGN KEY (`member_id`) REFERENCES `members`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`gameweek_id`) REFERENCES `gameweeks`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE UNIQUE INDEX `lineup_member_gw_uq` ON `lineups` (`member_id`,`gameweek_id`);",
      "CREATE TABLE `listings` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`league_id` integer NOT NULL,\n\t`player_id` integer NOT NULL,\n\t`seller_member_id` integer,\n\t`min_price` integer NOT NULL,\n\t`closes_at` integer NOT NULL,\n\t`status` text DEFAULT 'open' NOT NULL,\n\t`winner_member_id` integer,\n\t`final_price` integer,\n\tFOREIGN KEY (`league_id`) REFERENCES `leagues`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`player_id`) REFERENCES `players`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`seller_member_id`) REFERENCES `members`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `listings_league_idx` ON `listings` (`league_id`,`status`);",
      "CREATE TABLE `matches` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`gameweek_id` integer NOT NULL,\n\t`club_team_id` integer NOT NULL,\n\t`opponent` text NOT NULL,\n\t`is_home` integer DEFAULT true NOT NULL,\n\t`kickoff` integer NOT NULL,\n\t`status` text DEFAULT 'scheduled' NOT NULL,\n\t`goals_for` integer DEFAULT 0 NOT NULL,\n\t`goals_against` integer DEFAULT 0 NOT NULL,\n\t`minute` integer,\n\t`acta_url` text,\n\t`stats_applied` integer DEFAULT false NOT NULL,\n\t`updated_at` integer DEFAULT 0 NOT NULL,\n\tFOREIGN KEY (`gameweek_id`) REFERENCES `gameweeks`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`club_team_id`) REFERENCES `club_teams`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `matches_gw_idx` ON `matches` (`gameweek_id`);",
      "CREATE TABLE `members` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`league_id` integer NOT NULL,\n\t`user_id` integer NOT NULL,\n\t`team_name` text NOT NULL,\n\t`cash` integer NOT NULL,\n\t`created_at` integer NOT NULL,\n\tFOREIGN KEY (`league_id`) REFERENCES `leagues`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE UNIQUE INDEX `members_league_user_uq` ON `members` (`league_id`,`user_id`);",
      "CREATE TABLE `ownerships` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`league_id` integer NOT NULL,\n\t`member_id` integer NOT NULL,\n\t`player_id` integer NOT NULL,\n\t`bought_for` integer DEFAULT 0 NOT NULL,\n\t`acquired_at` integer NOT NULL,\n\tFOREIGN KEY (`league_id`) REFERENCES `leagues`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`member_id`) REFERENCES `members`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`player_id`) REFERENCES `players`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE UNIQUE INDEX `own_league_player_uq` ON `ownerships` (`league_id`,`player_id`);",
      "CREATE INDEX `own_member_idx` ON `ownerships` (`member_id`);",
      "CREATE TABLE `player_stats` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`match_id` integer NOT NULL,\n\t`player_id` integer NOT NULL,\n\t`minutes` integer DEFAULT 0 NOT NULL,\n\t`goals` integer DEFAULT 0 NOT NULL,\n\t`own_goals` integer DEFAULT 0 NOT NULL,\n\t`yellow` integer DEFAULT 0 NOT NULL,\n\t`red` integer DEFAULT false NOT NULL,\n\t`pen_saved` integer DEFAULT 0 NOT NULL,\n\t`pen_missed` integer DEFAULT 0 NOT NULL,\n\t`points` integer DEFAULT 0 NOT NULL,\n\t`value_delta` integer DEFAULT 0 NOT NULL,\n\tFOREIGN KEY (`match_id`) REFERENCES `matches`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`player_id`) REFERENCES `players`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE UNIQUE INDEX `stats_match_player_uq` ON `player_stats` (`match_id`,`player_id`);",
      "CREATE TABLE `players` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`club_team_id` integer NOT NULL,\n\t`name` text NOT NULL,\n\t`acta_name` text,\n\t`birth_date` text NOT NULL,\n\t`position` text NOT NULL,\n\t`shirt_number` integer,\n\t`value` integer DEFAULT 1000000 NOT NULL,\n\t`active` integer DEFAULT true NOT NULL,\n\tFOREIGN KEY (`club_team_id`) REFERENCES `club_teams`(`id`) ON UPDATE no action ON DELETE no action\n);",
      "CREATE INDEX `players_team_idx` ON `players` (`club_team_id`);",
      "CREATE TABLE `users` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`email` text NOT NULL,\n\t`name` text NOT NULL,\n\t`password_hash` text NOT NULL,\n\t`is_admin` integer DEFAULT false NOT NULL,\n\t`created_at` integer NOT NULL\n);",
      "CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);"
    ]
  }
];
